### ISSUE TITLE
Applying types to functions

### ISSUE THREAD

**Issue by assafcarlsbad** [synacktiv/bip#19]
Hi,

I'm trying to set the prototype for a function located at 0x31320. I'm using the `from_c` and `set_at` methods of `BipType`, but I'm still unable to set the type successfully. Am I doing something wrong or is it a current limitation of Bip itself?

```
pv = BipType.from_c("EFI_STATUS (*)(EFI_HANDLE, void *, void *, UINTN *)")

pv.set_at(0x31320)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-66-cd6f4f1c5d54> in <module>
----> 1 pv.set_at(0x31320)

C:/Users/carlsbad/AppData/Roaming/Hex-Rays/IDA Pro/plugins\bip\base\biptype.py in set_at(self, ea, flags)
    145         """
    146         if not apply_tinfo(ea, self._get_tinfo_copy(), flags):
--> 147             raise RuntimeError("Unable to set type {} at address {}".format(self.str, ea))
    148 
    149     @staticmethod

RuntimeError: Unable to set type EFI_STATUS (__fastcall *)(EFI_HANDLE, void *, void *, UINTN *) at address 201504
```

Thanks! 🙏

**Comment by BrunoPujos** [comment]
Hello,

So the error you got is for indicating that IDA (the `apply_tinfo` is the one from IDA) did not succeed in setting the type. There can be several reasons why this would happen, the two most common are because the address given is not "correct" (in general it would because in the middle of a defined element in IDA) or because the type is not correct.

In your case I believe this is a problem with the type: when you do `pv = BipType.from_c("EFI_STATUS (*)(EFI_HANDLE, void *, void *, UINTN *)")` this will define a function pointer (`BTypePtr` object pointing on a `BTypeFunc` object), for defining a function you would want directly the function type ( `BTypeFunc` object) which you can get with `pv = BipType.from_c("EFI_STATUS (f)(EFI_HANDLE, void *, void *, UINTN *)")`  (the name `f` is not important, you can make it what you want, but you will have to put one for the IDA parser to work).

I believe that just changing that should make you code works. You might have problems with hexrays (if you are using it) because the synchronization between the types is wierd. Hopefully what you are doing should work fine but you might want to check it.

Tell me if this work for you and by the way thank you for adding support of `SMM_Code_Chk_En` in chipsec :)

**Comment by BrunoPujos** [comment]
I hope the previous comment allowed you to fix your problem. I am closing this, do not hesitate to re-open if it did not fix your problem or if you have another issue.

**Comment by assafcarlsbad** [comment]
Thanks, works like a charm! 🙏
