### ISSUE TITLE
Searching for elements in the AST

### ISSUE THREAD

**Issue by assafcarlsbad** [synacktiv/bip#23]
Hi again,

In many cases I want to perform an analysis that searches the AST for nodes that meet certain criteria. To accomplish this, I often use the `visit_cnode_filterlist` method. However, since `visit_cnode_filterlist` does not return any value, I find it difficult to determine if the search yielded any results. To sidestep this limitation, I usually use the following two constructs:

1. Raising an exception to signal the termination of the search:

```
class StopCNodeVisit(Exception):
    pass

def callback(cnode):
	if ...: # Some condition involving cnode
		raise StopCNodeVisit()

try:
	hxcfunc.visit_cnode_filterlist(callback, [...])
except StopCNodeVisit:
	print('Element was found')
else:
	print('Element was not found')
```

2. Using closures:

```
def search_ast():
	found = False
	def callback(cnode):
		if ...: # Some condition involving cnode
			found = True
	hxcfunc.visit_cnode_filterlist(callback, [...])
	if found:
		print('Element was found')
	else:
		print('Element was not found')
```

Both solutions are pretty ugly and serve as temporary workarounds at best. The documentation for `visit_cnode_filterlist` states that: _"If this callback return False the visit is stopped"_. Is there any reason `visit_cnode_filterlist` doesn't propagate this value to the caller?

Thanks in advance 🙏

**Comment by BrunoPujos** [comment]
Hello,

Sorry for the delay.

If I understand correctly, in your case, you simply want to know if the search was interrupted because your callback returned False ? This is totally something we could do, simply returning False if the callback was interrupted. I actually think that is a pretty good idea.

However, it will only solve the first of your case, using closures will pretty much be mandatory in a lot of cases, a simple case such as counting the node of a particular type will require a closure, so this may not solve the full problem. The only way I see for fully solving this problem will be to provide a class/object allowing instrumentation of the visitor, which is probably something to do in the future but this will have to be well thought about and will probably not make usage any easier.

**Comment by BrunoPujos** [comment]
This has been done by #24: `visit_cnode_filterlist` and `visit_cnode` should now return True if they fully iterate on the AST or False if they were stop by the callback.

Hope this answer your request, do not hesitate to-reopen if not.
